spring:
  application:
    name: erbal-collect
  data:
      mongodb:
        host: localhost
        port: 27017
        database: erbal_db

server:
  port: 9001

security:
  basic:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

ribbon:
  eureka:
    enabled: true