spring:
  profiles:
    active: development

server:
  port: 9001
  context-path: /erbal-collector

---

spring:
  profiles: development

---

spring:
  profiles: production

#security:
#  oauth2:
#    client:
#      clientId: erbal-collector
#      clientSecret: erbal-collector
#      accessTokenUri: http://localhost:9090/uaa/oauth/token
#      grant-type: client_credentials
#      scope: server

