#server:
#  port: 8443  #https
#  ssl:
#    enabled: true
#    key-store: classpath:keystore.jks
#    key-store-password: erbalKeystor3
#    key-store-type: JKS
#    keyAlias: jetty

spring:
  profiles:
    active: development
server:
  port: 9999

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

---

spring:
  profiles: development

security:
    oauth2:
      client:
        access-token-uri: http://localhost:9090/erbal-uaa/oauth/token
        client-id: erbal-gateway
        client-secret: erbal-gateway
        user-authorization-uri: http://localhost:9090/erbal-uaa/oauth/authorize
      resource:
        user-info-uri: http://localhost:9090/erbal-uaa/user/current

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
      user:
        path: /user/**
        url: http://localhost:9090/erbal-uaa/user/current
      erbal-collector:
        path: /erbal-collector/**
        serviceId: erbal-collector
        stripPrefix: false
        sensitiveHeaders:
      erbal-greenhouse-management:
        path: /erbal-greenhouse-management/**
        serviceId: erbal-greenhouse-management
        stripPrefix: false
        sensitiveHeaders:
      erbal-notifier:
        path: /erbal-notifier/**
        serviceId: erbal-notifier
        stripPrefix: false
        sensitiveHeaders:
      erbal-retriever:
        path: /erbal-retriever/**
        serviceId: erbal-retriever
        stripPrefix: false
        sensitiveHeaders:

---

spring:
  profiles: production

security:
    oauth2:
      client:
        access-token-uri: http://borgo.ddns.net:9090/erbal-uaa/oauth/token
        client-id: erbal-gateway
        client-secret: erbal-gateway
        user-authorization-uri: http://borgo.ddns.net:9090/erbal-uaa/oauth/authorize
      resource:
        user-info-uri: http://borgo.ddns.net:9090/erbal-uaa/user/current

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
      user:
        path: /user/**
        url: http://borgo.ddns.net:9090/erbal-uaa/user/current
      erbal-collector:
        path: /erbal-collector/**
        serviceId: erbal-collector
        stripPrefix: false
        sensitiveHeaders:
      erbal-greenhouse-management:
        path: /erbal-greenhouse-management/**
        serviceId: erbal-greenhouse-management
        stripPrefix: false
        sensitiveHeaders:
      erbal-notifier:
        path: /erbal-notifier/**
        serviceId: erbal-notifier
        stripPrefix: false
        sensitiveHeaders:

#erbal:
#  cors:
#    allow-credentials: true
#    allowed-headers: origin, content-type, accept, authorization, X-Requested-With, Access-Control-Allow-Origin, Access-Control-Allow-Headers
#    allowed-methods: "GET, POST, OPTIONS"
#    allowed-origins: http://borgo.ddns.net:9090
#    max-age: 1800