#logging:
#  level:
#    org.springframework.security: INFO

turbine:
    clusterNameExpression: new String("default")

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

eureka:
  istance:
    hostname: borgo.ddns.net
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://borgo.ddns.net:8761/eureka/

spring:
  rabbitmq:
    host: localhost
    port: 5672  #15672 (http api show RabbitMQ stats) - 5672 (main port RabbitMQ)
    username: guest
    password: guest

#security:
#  oauth2:
#    resource:
#      user-info-uri: http://auth-service:5000/uaa/users/current
