server:
  port: 9001
  context-path: /erbal-collector

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

eureka:
  istance:
    hostname: localhost
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


#security:
#  oauth2:
#    client:
#      clientId: erbal-collector
#      clientSecret: erbal-collector
#      accessTokenUri: http://localhost:9090/uaa/oauth/token
#      grant-type: client_credentials
#      scope: server

spring:
  data:
    mongodb:
      host: localhost
      #username: admin
      #password: password
      database: erbal_db
      port: 27017
  rabbitmq:
    host: localhost
    port: 5672  #15672 (http api show RabbitMQ stats) - 5672 (main port RabbitMQ)
    username: guest
    password: guest