server:
  port: 9002
  context-path: /erbal-greenhouse-management

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

eureka:
  istance:
    hostname: http://borgo.ddns.net
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://borgo.ddns.net:8761/eureka/

spring:
  data:
    mongodb:
      host: localhost
      #username: admin
      #password: password
      database: erbal_db
      port: 27017