spring:
  profiles:
    active: development

server:
  port: 9090
  context-path: /erbal-uaa

---

spring:
  profiles: development

#Configuration injected in Authorization Server
erbal:
  oauth:
    redirectUri: http://localhost:9999

---

spring:
  profiles: production

#Configuration injected in Authorization Server
erbal:
  oauth:
    redirectUri: http://borgo.ddns.net:9999


#erbal:
#  cors:
#    allow-credentials: true
#    allowed-headers: origin, content-type, accept, authorization, X-Requested-With, Access-Control-Allow-Origin, Access-Control-Allow-Headers
#    allowed-methods: "GET, POST, OPTIONS"
#    allowed-origins: http://borgo.ddns.net:9999
#    max-age: 1800