server:
  port: 9090
  context-path: /erbal-uaa

eureka:
  istance:
    hostname: localhost
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  data:
    mongodb:
      host: localhost
      #username: user
      #password:
      database: erbal_db
      port: 27017