spring:
  profiles:
    active: development

server:
  port: 9002
  context-path: /erbal-greenhouse-management

---

spring:
  profiles: development

security:
  oauth2:
    client:
      clientId: erbal-greenhouse-management
      clientSecret: erbal-greenhouse-management
      accessTokenUri: http://localhost:9090/erbal-uaa/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://localhost:9090/erbal-uaa/user/current

---

spring:
  profiles: production

security:
  oauth2:
    client:
      clientId: erbal-greenhouse-management
      clientSecret: erbal-greenhouse-management
      accessTokenUri: http://borgo.ddns.net:9090/erbal-uaa/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://borgo.ddns.net:9090/erbal-uaa/user/current