spring:
  application:
    name: erbal-gateway

server:
  port: 9999

zuul:
  prefix: /api
  routes:
    erbal-collect:
      path: /erbal-collect/**
      url: http://localhost:9000

security:
  basic:
    enabled: false  #disable http basic auth

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/